projects:
  default:
    schema:
      - ../graph/schema/*.graphql
      - schema.graphql
      - ./$houdini/graphql/schema.graphql
    documents:
      - '**/*.gql'
      - ./$houdini/graphql/documents.gql
