query ListUsers ($filter: UserFilter){
    users(filter: $filter){
        items {
            node {
                ...UserFields
            }
        }
        pagination {
            itemsPerPage
            totalItems
        }
    }

}
