// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type DashboardMenus struct {
	SidebarTop    *Menu `json:"sidebarTop"`
	SidebarBottom *Menu `json:"sidebarBottom"`
}

type Error struct {
	String string `json:"string"`
	Status int    `json:"status"`
}

type FloatFilter struct {
	Eq         *bool      `json:"eq"`
	BeginsWith *bool      `json:"beginsWith"`
	EndsWith   *bool      `json:"endsWith"`
	Gt         *bool      `json:"gt"`
	Gte        *bool      `json:"gte"`
	Lt         *bool      `json:"lt"`
	Lte        *bool      `json:"lte"`
	And        *IntFilter `json:"and"`
	Or         *IntFilter `json:"or"`
}

type IntFilter struct {
	Eq         *bool      `json:"eq"`
	BeginsWith *bool      `json:"beginsWith"`
	EndsWith   *bool      `json:"endsWith"`
	Gt         *bool      `json:"gt"`
	Gte        *bool      `json:"gte"`
	Lt         *bool      `json:"lt"`
	Lte        *bool      `json:"lte"`
	And        *IntFilter `json:"and"`
	Or         *IntFilter `json:"or"`
}

type Menu struct {
	Items []*MenuItem `json:"items"`
}

type MenuItem struct {
	Name  *string `json:"name"`
	Icon  *string `json:"icon"`
	Route *string `json:"route"`
}

type Pagination struct {
	CurrentPage  *int `json:"currentPage"`
	PrevPage     *int `json:"prevPage"`
	NextPage     *int `json:"nextPage"`
	TotalItems   *int `json:"totalItems"`
	ItemsPerPage *int `json:"itemsPerPage"`
}

type PatientFilter struct {
	ID                  *string         `json:"ID"`
	FirstName           *StringFilter   `json:"FirstName"`
	LastName            *StringFilter   `json:"LastName"`
	Address             *StringFilter   `json:"Address"`
	DateOfBirth         *StringFilter   `json:"DateOfBirth"`
	Ethnicity           *StringFilter   `json:"Ethnicity"`
	Phn                 *StringFilter   `json:"Phn"`
	PrimaryRenalDisease *StringFilter   `json:"PrimaryRenalDisease"`
	Weight              *FloatFilter    `json:"Weight"`
	Height              *FloatFilter    `json:"Height"`
	Sex                 *StringFilter   `json:"Sex"`
	MaritalStatus       *StringFilter   `json:"MaritalStatus"`
	ContactNo           *StringFilter   `json:"ContactNo"`
	PersonType          *StringFilter   `json:"PersonType"`
	And                 *UserListFilter `json:"and"`
	Or                  *UserListFilter `json:"or"`
}

type PersonList struct {
	Persons    []*Person   `json:"persons"`
	Pagination *Pagination `json:"pagination"`
}

type StringFilter struct {
	Eq         *bool         `json:"eq"`
	Contains   *bool         `json:"contains"`
	BeginsWith *bool         `json:"beginsWith"`
	EndsWith   *bool         `json:"endsWith"`
	And        *StringFilter `json:"and"`
	Or         *StringFilter `json:"or"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UserList struct {
	Users      []*User     `json:"users"`
	Pagination *Pagination `json:"pagination"`
}

type UserListFilter struct {
	ID   *StringFilter   `json:"id"`
	Name *StringFilter   `json:"name"`
	And  *UserListFilter `json:"and"`
	Or   *UserListFilter `json:"or"`
}

type UserLogin struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UserToken struct {
	Token string `json:"token"`
	Error *Error `json:"error"`
	User  *User  `json:"user"`
}
